codecov:
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "00...100"

ignore:
  - ".github/workflows"  # ignore folders and all its contents
  - ".gradle/"
  - ".settings/"
  - "gradle/wrapper/"
  - "lib/.settings/"
  - "lib/bin/"
  - "lib/build/"
  - "lib/src/test/java/TemporaryGroupGradle/"
  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
